//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlowfishNET.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlowfishNET.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CBC encrypted data was decrypted successfully. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_CBC_DECRYPT_OK {
            get {
                return ResourceManager.GetString("BFDEMO_CBC_DECRYPT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data mismatch detected at position {0}! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_DATAMISMATCH_1 {
            get {
                return ResourceManager.GetString("BFDEMO_DATAMISMATCH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decryption error at position {0}! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_DECRYPT_ERROR_1 {
            get {
                return ResourceManager.GetString("BFDEMO_DECRYPT_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected oversized data! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_DECRYPT_OVERSIZED {
            get {
                return ResourceManager.GetString("BFDEMO_DECRYPT_OVERSIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECB encrypted data was decrypted successfully. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_ECB_DECRYPT_OK {
            get {
                return ResourceManager.GetString("BFDEMO_ECB_DECRYPT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running performance test... 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_RUNNING_PERFORMANCE {
            get {
                return ResourceManager.GetString("BFDEMO_RUNNING_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selftest failed! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SELFTEST_FAILED {
            get {
                return ResourceManager.GetString("BFDEMO_SELFTEST_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selftest passed. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SELFTEST_PASSED {
            get {
                return ResourceManager.GetString("BFDEMO_SELFTEST_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlowfishSimple decryption failed unexpectedly! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SIMPLE_FLAW {
            get {
                return ResourceManager.GetString("BFDEMO_SIMPLE_FLAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected match of the wrong password! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SIMPLE_UNEXPECTED_MATCH {
            get {
                return ResourceManager.GetString("BFDEMO_SIMPLE_UNEXPECTED_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected mismatch of the right password! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SIMPLE_UNEXPECTED_MISMATCH {
            get {
                return ResourceManager.GetString("BFDEMO_SIMPLE_UNEXPECTED_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} bytes per second. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_SPEED_RESULT_1 {
            get {
                return ResourceManager.GetString("BFDEMO_SPEED_RESULT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream decrypted successfully. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_STREAM_DECRYPT_OK {
            get {
                return ResourceManager.GetString("BFDEMO_STREAM_DECRYPT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weak key detected! 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_WEAK_KEY_DETECTED {
            get {
                return ResourceManager.GetString("BFDEMO_WEAK_KEY_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} bytes written to stream, total size is {1}. 的本地化字符串。
        /// </summary>
        internal static string BFDEMO_WRITTEN_TO_STREAM_2 {
            get {
                return ResourceManager.GetString("BFDEMO_WRITTEN_TO_STREAM_2", resourceCulture);
            }
        }
    }
}
