//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlowfishNET.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlowfishNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid block size. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_BLOCKSIZE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_BLOCKSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only ECB and CBC modes are supported. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_CIPHERMODE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_CIPHERMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid IV length. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_IV_LENGTH {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_IV_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid key size. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_KEYSIZE {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_KEYSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PKCS7 padding data {0} at {1}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_PADDATA_PKCS7_2 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADDATA_PKCS7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ANSIX923 padding value {0}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_PADVAL_ANSIX923_1 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADVAL_ANSIX923_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PKCS7 padding value {0}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_INVALID_PADVAL_PKCS7_1 {
            get {
                return ResourceManager.GetString("BFALGO_INVALID_PADVAL_PKCS7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nonzero ANSIX923 padding data {0} at {1}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_NONZERO_PADDATA_ANSIX923_2 {
            get {
                return ResourceManager.GetString("BFALGO_NONZERO_PADDATA_ANSIX923_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected last block count {0}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_UNEXPECTED_LAST_BLOCK_COUNT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNEXPECTED_LAST_BLOCK_COUNT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown padding {0} for final decryption. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_UNKNOWN_PADDING_DECRYPT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNKNOWN_PADDING_DECRYPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown padding {0} for final encryption. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_UNKNOWN_PADDING_ENCRYPT_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNKNOWN_PADDING_ENCRYPT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported padding mode {0}. 的本地化字符串。
        /// </summary>
        internal static string BFALGO_UNSUPPORTED_PADDINGMODE_1 {
            get {
                return ResourceManager.GetString("BFALGO_UNSUPPORTED_PADDINGMODE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read IV, no more data. 的本地化字符串。
        /// </summary>
        internal static string JAVAIOP_CANNOT_READ_IV {
            get {
                return ResourceManager.GetString("JAVAIOP_CANNOT_READ_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid padding pattern. 的本地化字符串。
        /// </summary>
        internal static string JAVAIOP_INVALID_PADDING_PATTERN {
            get {
                return ResourceManager.GetString("JAVAIOP_INVALID_PADDING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid padding value. 的本地化字符串。
        /// </summary>
        internal static string JAVAIOP_INVALID_PADVAL {
            get {
                return ResourceManager.GetString("JAVAIOP_INVALID_PADVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last block is truncated. 的本地化字符串。
        /// </summary>
        internal static string JAVAIOP_LAST_BLOCK_TRUNCATED {
            get {
                return ResourceManager.GetString("JAVAIOP_LAST_BLOCK_TRUNCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data is truncated. 的本地化字符串。
        /// </summary>
        internal static string JAVAIOP_TRUNCATED {
            get {
                return ResourceManager.GetString("JAVAIOP_TRUNCATED", resourceCulture);
            }
        }
    }
}
